"""
Flaming News - PMS Special Request / Guest Attribute Codes
Full reference table (as provided by the hotel) mapping 2-4 letter PMS
"Specials:" codes to their meaning. Used to translate SA (Special
Attention) guests' raw codes into readable remarks.
"""

FULL_CODES = {
    '0B': 'No Bed Preference',
    '1B': '1 Bed Requested',
    '1F': '1st Floor',
    '1S': '1 Bdrm Suite Requested',
    '2B': '2 Beds Requested',
    '2D': '2 Double Beds Requested',
    '2S': '2 Bdrm Suite Requested',
    'AA': 'Advised Guest Smoking Pref in N/A',
    'AB': 'Activity Booking',
    'AD': 'Adjacent room',
    'AE': 'Away from Elevator',
    'AH1': 'ALL Elite tier member',
    'AK': 'Amenity Kit',
    'AN': 'Anniversary',
    'ANN': 'Anniversary',
    'AR': 'Activity Requested',
    'ARP': 'Airport Transfer',
    'AS': 'Needs Assistance - Warning',
    'B6': 'Billing Requested',
    'BAB': 'Baby Highchair',
    'BAT': 'Bathrobe',
    'BB': 'Bed Board Requested',
    'BC': 'Business Services Room',
    'BD': 'Birthday',
    'BDY': 'Birthday',
    'BG': 'Baggage Gratuity',
    'BL': 'Balcony Requested',
    'BS': 'Babysitting Requested',
    'BST': 'Baby sitter',
    'BT': 'Billing Approved',
    'CBQ': 'Card from BQT MGR',
    'CEM': 'Card from EAM',
    'CFO': 'Card from FOM',
    'CGM': 'Card from GENERAL MGR',
    'CGR': 'Card from GST REL.',
    'CH': 'Chain Reservation',
    'CHP': 'Champagne',
    'CM': 'Circle Member',
    'CN': 'Connecting Room',
    'CO': 'Corner Room Requested',
    'COT': 'Cot Required',
    'CPR': 'Card from PR MGR',
    'CR': 'Crib Requested',
    'CSA': 'Card from SALES MGR',
    'CT': 'Rollaway Requested',
    'CV': 'City View Requested',
    'CWIF': 'ALLMember-FreeWiFi',
    'D3': 'See Comments Field',
    'DAY': 'Day Use',
    'DBL': 'Dble Bed REQD',
    'DIV': 'Divan/Sofa Made Up',
    'DM': 'Do Not Move',
    'DU': 'Day Use Room',
    'DV': 'Distinguished Visitor/Special Guest',
    'DW': 'Do Not Walk',
    'EAA': 'Early Arrival',
    'EC': 'Early Check-In Requested',
    'FA': 'Food Allergies',
    'FE': 'Feather Pillows Requested',
    'FF': 'Fairmont Fit',
    'FG': 'Fairmont Gold Guest',
    'FGD': 'Fairmont Gold only Dinner',
    'FI': 'Fireplace',
    'FLW': 'Flowers',
    'FN': 'Fan',
    'FP': 'Foam Pillows',
    'FRB': 'Fruit Basket',
    'FS': 'Forced Sell',
    'FT': 'Financial Times Newspaper',
    'FV': 'Fairmont Visa Signature Introduced',
    'FX': 'Fax Confirmation',
    'GR': 'Guest Recovery',
    'H1': 'High Speed Internet Access',
    'HC': 'Needs Assistance - Mobility',
    'HF': 'High Floor',
    'HI': 'Needs Assistance - Hearing',
    'HIG': 'High Floor',
    'HM': 'Honeymoon',
    'HR': 'Honeymooners',
    'HU': 'Humidifier',
    'I5': 'Wall Street Journal - FPC',
    'I6': 'USA Today - FPC',
    'I7': 'Boston Globe',
    'I9': 'New York Times - FPC',
    'I10': 'National Post',
    'I11': 'Globe & Mail',
    'I12': 'Herald Tribune',
    'IA': 'National Newspaper',
    'IC': 'No Newspaper Delivery',
    'II': 'Industry Influencer',
    'INT': 'Interconnecting',
    'IRB': 'Iron & Board',
    'JG': 'Japanese Guest',
    'JR': 'Jacuzzi Requested',
    'KG': 'King Bed',
    'KNG': 'King Bed Request',
    'LA': 'Late Arrival',
    'LAD': 'Late Departure',
    'LC': 'Late Check Out',
    'LF': 'Low Floor Requested',
    'LOW': 'Low Floor',
    'LS': 'Long Stay Guests',
    'MA': 'Muslim Amenity',
    'MI': 'Microwave Requested',
    'MP': 'Marco Polo Member',
    'NB': 'Request rooms near by',
    'NE': 'Near Elevator',
    'NI': 'Near Ice Machine',
    'NPE': 'Local Newspaper English',
    'NS': 'Non Smoking',
    'NT': 'Local Paper',
    'PA': 'Travelling With',
    'PE': 'Pet Accompanying Guest',
    'PF': 'Package on the Fly',
    'PG': 'Parking Fee',
    'PO': 'Sofa Bed Requested',
    'PR': 'Pre-Register Guest',
    'PT': 'Pre & Post Tour',
    'QC': 'Quality Control Checks',
    'QN': 'Queen',
    'QR': 'Quiet Room',
    'QTR': 'Quiet Room',
    'R1': 'Relocated Guest',
    'R2': 'RA Premier Member',
    'R3': 'RA Ambassadors Member',
    'R4': 'RA VVIP Member',
    'RA': 'Room change during stay',
    'RB': 'Minibar requested',
    'RBK': 'Restaurant BKNG',
    'RD': 'Restrict Video Folio Display',
    'RG': 'Repeat Guest',
    'RI': 'Refridgerator',
    'RM': 'Restrict Movies',
    'ROL': 'Rollaway Bed',
    'RS': 'Rate Change',
    'RT': 'Restrict Video Rm & Tx',
    'RV': 'Restrict Video Checkout',
    'S1': 'Inizia Online Circle',
    'S2': 'Inizia Lifetime Circle',
    'S3': 'Eleva Circle',
    'S4': 'Zenit Circle',
    'S5': 'Zenit Partner Circle',
    'SA': 'Recovery Guests - Special Attention',
    'SBK': 'Silent Booking',
    'SC': 'Special Occasion',
    'SE': 'Shower',
    'SK': 'Smoking room requested',
    'SMR': 'Smoking Room REQ',
    'SO': 'Stayover requested',
    'SP': 'Special newspaper',
    'SR': 'Service Recovery',
    'SV': 'Service Charge',
    'SW': 'Share with reservation',
    'T1': 'ALL Classic Member',
    'T2': 'ALL Silver Member',
    'T3': 'ALL Gold Member',
    'T4': 'ALL Platinum Member',
    'T5': 'ALL Diamond Member',
    'T6': 'ALL Limitless Member',
    'TD': 'Turndown',
    'TU': 'Bathtub',
    'TWN': 'Twin Beds',
    'UP': 'Upgrade requested',
    'UPG': 'Upgrade GTD',
    'UPR': 'Upgrade Requested',
    'UR': 'Upgraded Room per Admin/Sales',
    'US': 'Upsell',
    'V1': 'VIP',
    'VI': 'Needs Assistance - Visual',
    'VP': 'Voucher Payment',
    'VW': 'View Requested',
    'VWG': 'View GTD',
    'VWR': 'View Requested',
    'VX': 'View Guaranteed',
    'W1': 'Fruit in Season',
    'W2': 'Healthy Obsession',
    'W3': 'Sweet Surrender (pastries, cookies)',
    'W4': 'Chocolate Delight',
    'W5': 'Cheese & Grapes',
    'W6': 'Surprise Me authentically local amenity',
    'WC': 'Needs Assistance - Wheelchair',
    'WV': 'Water View Requested',
    'WX': 'Written Confirmation',
    'XB': 'Non Eligible',
    'Z1': 'Per General Manager',
    'Z2': 'Per DOSM',
    'Z3': 'Per Front Office Mgmt',
    'Z4': 'Per Public Relations',
    'Z5': 'Per Sales/Conf. Svcs',
    'ZG': 'First Time Stay',
    'ZT': 'For Hotel Use Only',
    'ZU': 'For Hotel Use Only',
    'ZV': 'For Hotel Use Only',
    'ZW': 'For Hotel Use Only',
    'ZX': 'For Hotel Use Only',
    'ZY': 'For Hotel Use Only',
    'ZZ': '—',
}

# Ordered priority list of "occasion" code groups worth surfacing as a VIP
# remark (as opposed to purely operational codes like room/pillow prefs).
# First match in this order wins for each guest; a guest can match more
# than one group (e.g. Birthday + Anniversary), joined with ', '.
OCCASION_GROUPS = [
    (('BD', 'BDY'), 'Birthday'),
    (('AN', 'ANN'), 'Anniversary'),
    (('HM', 'HR'), 'Honeymooners'),
    (('GR', 'SR'), 'Recovery'),
    (('SC',), 'Special Occasion'),
    (('ZG',), 'First Time Stay'),
    (('RG',), 'Repeat Guest'),
    (('II',), 'Industry Influencer'),
]


def match_occasions(raw_code_tokens):
    """
    raw_code_tokens: list of upper-cased code strings (already split/cleaned).
    Returns (labels, matched_codes, unmatched_codes) where labels is the
    ordered list of occasion labels found (e.g. ['Birthday', 'Recovery']),
    matched_codes is which raw tokens were consumed, and unmatched_codes is
    whatever's left (operational codes we don't turn into a remark, or truly
    unknown codes).
    """
    tokens = set(raw_code_tokens)
    labels = []
    matched = set()
    for codes_group, label in OCCASION_GROUPS:
        hit = tokens.intersection(codes_group)
        if hit:
            labels.append(label)
            matched.update(hit)
    unmatched = [t for t in raw_code_tokens if t not in matched]
    return labels, matched, unmatched
